# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxBindUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxBindUI
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'RxDataSources'
end
